### ISSUE TITLE
apcupsd_exporter: move hostname, model, and ups_name labels to an info metric

### ISSUE THREAD

**Issue by mdlayher** [mdlayher/apcupsd_exporter#6]
These are all redundant on every time series, and should be moved to an info metric that can be joined on as needed.

**Comment by jangrewe** [comment]
Just noticed that this is really a good idea! When testing i unplugged the USB cable to simulate the `COMMLOST` status (which worked fine), but that also dropped the `model` label from all metrics - resulting in "Multple Series" errors in Grafana, because there was now one metric with the `model` label and one without it.

**Comment by jangrewe** [comment]
This should be implemented with #8
